spring:
  application:
    name: 'microservice-gs-2023'

# PRÉ-CONFIGURAÇÃO DO BANCO DE DADOS QUANDO FOR IMPLEMENTADO    
#  datasource:
#    url: ${jdbc.url}
#    username: ${jdbc.username}
#    password: ${jdbc.password}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
